language: node_js
node_js:
  - "7"
install:
  - npm install
script:
  - gulp clean
  - gulp embedded
  - gulp build
  - gulp testsToGhPages
  - npm test
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: 'build'
    github_token: $GITHUB_TOKEN
    on:
      branch: master
